theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1:
  - formatselect
  - fontselect
  - fontsizeselect
  - styleselect
  - removeformat
theme_advanced_buttons2:
  - hr  
  - sub
  - sup
  - forecolor
  - backcolor
  - forecolorpicker
  - backcolorpicker
  - charmap
  - visualaid
  - anchor
  - newdocument
  - separator
  - blockquote
theme_advanced_buttons3:
  - bold
  - italic
  - underline
  - strikethrough
  - justifyleft
  - justifycenter
  - justifyright
  - justifyfull
  - bullist
  - numlist
  - outdent
  - indent
  - cut
  - copy
  - paste
  - undo
  - redo
  - link
  - unlink
  - uploadimage
  - cleanup
  - fullscreen  
  - help
  - code
plugins:
  - table
  - fullscreen
  - uploadimage